debug: false
spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: "/*"
      stat-view-servlet:
        login-username: admin
        login-password: adminto
      username: root
      password: adminto
      url: 'jdbc:mysql://127.0.0.1:3306/spring_batch?useUnicode=true&amp;characterEncoding=utf8'
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
            multi-statement-allow: true

server:
  port: 8888

management:
  security:
    enabled: false